export const SERVICES_TO_SEED = [
    { name: "Manicura Luna Silver", priceBase: 55.00, category: "Menú Regular de Manos y Pies" },
    { name: "Soft Gel Pro", priceBase: 85.00, category: "Menú Regular de Manos y Pies" },
    { name: "Uñas Estructuradas (Esculpidas)", priceBase: 120.00, category: "Menú Regular de Manos y Pies" },
    { name: "Baño de Poligel / Builder Gel (Capping)", priceBase: 75.00, category: "Menú Regular de Manos y Pies" },
    { name: "Pedicura Luz de Luna", priceBase: 80.00, category: "Menú Regular de Manos y Pies" },
    { name: "Belleza de Manos y Pies Completa", priceBase: 120.00, category: "Menú Regular de Manos y Pies" },
    { name: "Servicio Express Dual (Manos y Pies)", priceBase: 100.00, category: "Menú Regular de Manos y Pies" },
    { name: "Retiro de Gel", priceBase: 20.00, category: "Menú Regular de Manos y Pies" },
    { name: "Retiro de Sistema", priceBase: 35.00, category: "Menú Regular de Manos y Pies" },
    { name: "Diseño Eclipse (Diseño Especial)", priceBase: 10.00, category: "Menú Regular de Manos y Pies" },
    { name: "Upgrade a Semipermanente", priceBase: 20.00, category: "Menú Regular de Manos y Pies" },
    { name: "Exfoliación Orgánica Premium", priceBase: 10.00, category: "Menú Regular de Manos y Pies" },
    { name: "Reconstrucción de Uña Individual", priceBase: 10.00, category: "Menú Regular de Manos y Pies" },
    { name: "Maquillaje Social Luz de Luna", priceBase: 100.00, category: "Maquillaje Social y Quinceañeras" },
    { name: "Maquillaje Social Glam Night", priceBase: 120.00, category: "Maquillaje Social y Quinceañeras" },
    { name: "Maquillaje Mis 15 (Mi Día Soñado)", priceBase: 350.00, category: "Maquillaje Social y Quinceañeras" },
    { name: "Preparación de Piel VIP (Lifting Flash)", priceBase: 30.00, category: "Maquillaje Social y Quinceañeras" },
    { name: "Diseño de Cejas Express", priceBase: 15.00, category: "Maquillaje Social y Quinceañeras" },
    { name: "Aplicación de Pestañas Premium de Tira o Grupales", priceBase: 20.00, category: "Maquillaje Social y Quinceañeras" },
    { name: "Masaje Relajante Cuerpo Entero", priceBase: 90.00, category: "Masaje y Cuidado Capilar" },
    { name: "Masaje Relajante Medio Cuerpo", priceBase: 40.00, category: "Masaje y Cuidado Capilar" },
    { name: "Masaje Descontracturante Cuerpo Entero", priceBase: 100.00, category: "Masaje y Cuidado Capilar" },
    { name: "Masaje Descontracturante Medio Cuerpo", priceBase: 30.00, category: "Masaje y Cuidado Capilar" },
    { name: "Tinturación de Cabello (Corto)", priceBase: 40.00, category: "Masaje y Cuidado Capilar" },
    { name: "Tinturación de Cabello (Mediano)", priceBase: 80.00, category: "Masaje y Cuidado Capilar" },
    { name: "Tinturación de Cabello (Largo)", priceBase: 120.00, category: "Masaje y Cuidado Capilar" },
    { name: "Paquete Novia Esencial", priceBase: 550.00, category: "Servicios Exclusivos de Novia (Luna Bridal)" },
    { name: "Paquete Novia Radiante", priceBase: 880.00, category: "Servicios Exclusivos de Novia (Luna Bridal)" },
    { name: "Paquete Experiencia Luna Premium", priceBase: 1250.00, category: "Servicios Exclusivos de Novia (Luna Bridal)" }
];
